# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotedby', models.CharField(max_length=26)),
                ('message', models.CharField(max_length=26)),
                ('counter', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoting_user', to='login_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='poke',
            name='poked',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='poker',
        ),
        migrations.DeleteModel(
            name='Poke',
        ),
    ]
